## Server port
server:
  port: 9993

## H2 Configuration
spring:
  h2:
    console:
      enabled: true
      path: /anusha
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:anusha_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: anusha
    password: anusha
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true
